---
- name: Pre-requisite packages installation
  package:
    name:
      - tar
      - gzip
      - curl
    state: present

- name: Execute installation tasks
  include_tasks: install.yml

- name: execute configuration tasks
  include_tasks: configure.yml
