---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded

- name: Reload Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted


